### ISSUE TITLE
Matching Intents and Skills

### ISSUE THREAD

**Issue by sarahsporck** [DasNeuling/RohBot#9]
As for now matching the intents/skills is still missing I´d like to state some ideas to what would be nice to have in this matcher:

- clear text matching as well as command matching:
-> this means as well 'weather Augsburg' as 'What is the weather in Augsburg' and that the commands do not need to have any order
- matching and then passing parameters to the corresponding 'execute'
- maybe add error handling here for lower level functions? try/expect send_message(chat_id, e)?

**Comment by andreas-grafberger** [comment]
Regarding the text matching: These features should definitely be supported.
Nevertheless, I'm unsure about the matching and passing of parameters to the corresponding execute.
I suppose, extracting the relevant parameters from the users utterance should be done by the Skill itself.
